
export const JIKAN = 'https://api.jikan.moe/v4';
export const TMDB = 'https://api.themoviedb.org/3';
export const TMDB_IMG = 'https://image.tmdb.org/t/p';

export const INJECT_LIST: any[] = [
  // Em andamento
  [38707,   2, 3, 1, 'continuar', ['meio'],              'T3 finalizada — T4 sem previsão'],
  [108465,  4, 2, 1, 'continuar', ['meio','ficar'],      'T3 confirmada — Julho 2026', 'b-s', 'S3 Jul/2026'],
  [151807, 11, 2, 1, 'continuar', ['meio'],              '⚡ Faltam só 15 eps!'],
  [157897,  4, 2, 1, 'continuar', ['meio']],
  [140196,  1, 2, 1, 'continuar', ['meio']],
  [32949,   5, 1, 1, 'continuar', ['meio'],              'T1 e T2 com PT-BR'],
  [170516,  8, 1, 1, 'continuar', ['meio','ficar'],      'T2 anunciada para 2026', 'b-s', 'S2 2026'],
  [32901,   1, 1, 1, 'continuar', ['meio'],              'T2 anunciada em 2021, sem data'],
  [119456,  2, 1, 1, 'continuar', ['meio'],              'Série completa: 24 eps em 2 partes'],
  [160166,  1, 1, 1, 'continuar', ['meio']],
  [130298,  1, 1, 1, 'continuar', ['meio']],
  [139636,  3, 1, 1, 'continuar', ['meio']],
  [175441, 10, 1, 1, 'seguir',    ['meio'],              '⚡ Faltam só 2 eps!'],
  [168175,  7, 1, 1, 'seguir',    ['meio','ficar'],      'T2 anunciada, sem data', 'b-e', 'T2 a vir'],
  [170512,  3, 1, 1, 'seguir',    ['meio']],
  [154391,  6, 1, 1, 'seguir',    ['meio'],              'T2 do especial disponível'],
  [57030,   1, 1, 0, 'continuar', ['meio'],              'Apenas EN dub, sem PT-BR'],
  [162804,  1, 1, 0, 'continuar', ['meio'],              'Sem PT-BR na Crunchyroll'],
  [161645,  6, 1, 0, 'seguir',    ['meio'],              'Sem PT-BR confirmado'],
  // Assistir de novo / terminado
  [52991,  12, 2, 1, 'novamente', ['nova-tp','term','ficar'], 'T2 completa! T3 sem data', 'b-w', 'T2 ok'],
  // Não comecei
  [101764,  0, 1, 1, 'comecar',   ['nova-tp','nc'],      'T1 e T2 com PT-BR'],
  [18617,   0, 1, 0, 'comecar',   ['nova-tp','nc'],      'OVA do anime de 2013 — sem PT-BR'],
  [46102,   0, 1, 1, 'comecar',   ['nc']],
  [109080,  0, 1, 0, 'comecar',   ['nc'],                'Dub EN disponível, sem PT-BR'],
  [103940,  0, 1, 0, 'comecar',   ['nc'],                'Dub EN disponível, sem PT-BR'],
  [169805,  0, 1, 0, 'comecar',   ['nc'],                'Sem PT-BR confirmado'],
  [167896,  0, 1, 0, 'comecar',   ['nc'],                'Sem PT-BR confirmado'],
];

export const INJECT_BY_NAME: any[] = [
  { q:'Ousama Ranking',                title:'Ranking of Kings',                        ep:0,s:1,dub:1,st:'comecar',lists:['nc'] },
  { q:'Metallic Rouge',                title:'Metallic Rouge',                          ep:0,s:1,dub:1,st:'comecar',lists:['nc'] },
  { q:'Kaifuku Jutsushi no Yarinaoshi',title:'The Healer Banished from His Party',      ep:0,s:1,dub:1,st:'comecar',lists:['nc'] },
  { q:'Raise wa Tanin ga Ii',          title:'Yakuza Fiancé: Raise wa Tanin ga Ii',     ep:0,s:1,dub:1,st:'comecar',lists:['nc'] },
];

export const GENRE_PT: Record<string, string> = {
  'Action':           'Ação',
  'Adventure':        'Aventura',
  'Comedy':           'Comédia',
  'Drama':            'Drama',
  'Fantasy':          'Fantasia',
  'Horror':           'Terror',
  'Mystery':          'Mistério',
  'Psychological':    'Psicológico',
  'Romance':          'Romance',
  'Sci-Fi':           'Ficção Científica',
  'Science Fiction':  'Ficção Científica',
  'Slice of Life':    'Slice of Life',
  'Sports':           'Esportes',
  'Supernatural':     'Sobrenatural',
  'Suspense':         'Suspense',
  'Thriller':         'Suspense',
  'Ecchi':            'Ecchi',
  'Mecha':            'Mecha',
  'Music':            'Música',
  'School':           'Escolar',
  'Shounen':          'Shounen',
  'Shoujo':           'Shoujo',
  'Seinen':           'Seinen',
  'Josei':            'Josei',
  'Military':         'Militar',
  'Police':           'Policial',
  'Historical':       'Histórico',
  'History':          'Histórico',
  'Demons':           'Demônios',
  'Samurai':          'Samurai',
  'Magic':            'Magia',
  'Space':            'Espaço',
  'Martial Arts':     'Artes Marciais',
  'Super Power':      'Super Poder',
  'Vampire':          'Vampiro',
  'Harem':            'Harém',
  'Game':             'Game',
  'Parody':           'Paródia',
  'Kids':             'Infantil',
  'Isekai':           'Isekai',
  'Award Winning':    'Premiado',
  'Gourmet':          'Gastronomia',
  'Racing':           'Corrida',
  'Strategy Game':    'Jogo de Estratégia',
  'Crossdressing':    'Crossdressing',
  'Gore':             'Gore',
  'Survival':         'Sobrevivência',
  'Time Travel':      'Viagem no Tempo',
  'Mythology':        'Mitologia',
  'Reincarnation':    'Reencarnação',
  'Delinquents':      'Delinquentes',
  'Love Polygon':     'Polígono Amoroso',
  'Performing Arts':  'Artes Cênicas',
  'Adult Cast':       'Elenco Adulto',
  'Anthropomorphic':  'Antropomórfico',
  'High Stakes Game': 'Jogo de Alto Risco',
  'Iyashikei':        'Iyashikei',
  'Reverse Harem':    'Reverse Harém',
};
